#!/usr/bin/env ruby

#require 'rubygems'
require 'yaml'
require "vici"
require "socket"

# By default socket path "/var/run/charon.vici"
# Vici::Connection.new(UNIXSocket.new("/var/run/charon.vici"))
sock = Vici::Connection.new()

uptime = sock.stats["uptime"]["running"].split(' ')

puts "graph_title Strongswan ipsec uptime"
puts "graph_category ipsec"
puts "graph_vlabel uptime #{ uptime[1] }"
puts "graph_info This graph monitors the uptime"

puts "uptime.label Uptime"
puts "uptime.min 0"
puts "uptime.draw AREA"


puts "uptime.value #{ uptime[0] }"
