#!/usr/bin/env ruby

require 'yaml'
require "vici"
require "socket"

# By default socket path "/var/run/charon.vici"
# Vici::Connection.new(UNIXSocket.new("/var/run/charon.vici"))
sock = Vici::Connection.new()

stats_json = sock.stats

puts "graph_title Strongswan workers"
puts "graph_category ipsec"
puts "graph_vlabel workers_count"
puts "graph_info This graph monitors the strongswan workers rate"

puts "workers_total.label workers_total"
puts "workers_total.min 0"
puts "workers_total.draw AREA"

puts "workers_idle.label workers_idle"
puts "workers_idle.min 0"
puts "workers_idle.draw AREA"

puts "workers_total.value #{stats_json["workers"]["total"]}"
puts "workers_idle.value #{stats_json["workers"]["idle"]}"

